import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './components/Navbar';
import Footer from './components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />

        {/* ✅ WhatsApp Chat Button */}
        <a
          href="https://wa.me/255744381263"
          target="_blank"
          rel="noopener noreferrer"
          className="fixed bottom-5 right-5 z-50"
        >
          <img
            src="/whatsapp.png"
            alt="Chat on WhatsApp"
            className="w-12 h-12 shadow-lg hover:scale-105 transition rounded-full"
          />
        </a>
      </body>
    </html>
  );
}
